version: "3.5"

# networks:
#   inception:
#     name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
     - "443:443"
    # networks:
    #  - inception
    env_file:
      - .env
    restart: always
  # wordpress:
  #   image: wordpress:latest
  #   ports:
  #     - 80:80
  #   restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file:
      - .env
    restart: always

