version: "3.5"

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
     - "443:443"
    networks:
     - inception
    env_file:
      - .env
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  redis:
    container_name: redis
    build: ./requirements/bonus/redis/.
    networks:
      - inception
    restart: always
  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
     - "8083:80"
    restart: always
  ftp-server:
    container_name: ftp-server
    build: ./requirements/bonus/ftp-server/.
    depends_on:
      - wordpress
    ports:
      - "21:21"
      - "20:20"
      - "64000-64321:64000-64321"
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wp_data:/home/ftp_simon/ftp
    restart: always
  website:
    container_name: website
    build: ./requirements/bonus/website/.
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    restart: always



volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      type: none
      device: /home/skunert/data/db_data
      o: bind
  wp_data:
    name: wp_data
    driver: local
    driver_opts:
      type: none
      device: /home/skunert/data/wp_data
      o: bind
