version: "3.5"

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
     - "443:443"
    networks:
     - inception
    env_file:
      - .env
    # volumes:
      # - wp_data: /var/www/html
    restart: always
  # wordpress:
  #   image: wordpress:latest
  #   ports:
  #     - 80:80
  #   networks:
  #     - inception
  #   volumes:
  #     - wp_data: /var/www/html
  #   restart: always
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
#   wp_data:
